### ISSUE TITLE
Tutorial how to start / connect

### ISSUE THREAD

**Issue by asern1989** [suletom/EASUN-ISOLAR-SMX-II-CONTROL#1]
Please wiki how to start

**Comment by suletom** [comment]
Hi,Thank you for your interest. This project is in very early pre-alpha stage. Unfortunately the seller/"manufaturer" refused to provide any documentation about the device, thats why i started to reverse engineer the wifi modbus tcp gateway device capabilites.Today i succeeded in getting the parameters from my device, but there is a lot more work to do.I'll update the readme as soon as i can. Wanna try the app on your device? What kind of inverter/wifi device you have?Are you familiar with linux/nodejs?Regards,Tom-------- Eredeti levél --------Feladó: asern1989 ***@***.***>Dátum: 2022 november 23 13:57:28Tárgy: [suletom/EASUN-ISOLAR-SMX-II-CONTROL] Tutorial how to start / connect (Issue #1)Címzett: suletom/EASUN-ISOLAR-SMX-II-CONTROL ***@***.***>Please wiki how to start—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by asern1989** [comment]
EASUN-ISOLAR-SMX-II 5.6 kW
I'm learning fast, give me a link on what to install and how to run the rest, I can handle it
